//
//
// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
// 

/**
 * Consolidated client environment type declarations
 * 
 * This file is auto-generated by env-map.generate.ts
 */



declare global {
  interface Window {
    env: {
      // The app environment (development, production, preview, staging)
      PUBLIC_APP_ENV?: string;
      // The fully qualified domain name of the application (e.g., example.com or localhost:3000)
      PUBLIC_APP_FQDN?: string;
    };
  }
}

/**
 * Export all client environments for easy access
 */
export {

};