// This file is generated automatically by scripts/generate-routes.ts
// Do not edit this file directly.
// To regenerate this file, run:
//   yarn generate-routes
//
import { components, hooks, utils } from "~/lib/router/generouted-components";

// all paths get defined here...
export const routePaths = [
  "/",
  "/admin",
  "/admin/orders/:orderId/manufacturer-xlsx",
  "/api/actions",
  "/auth/google",
  "/auth/google/callback",
  "/cart",
  "/checkout",
  "/confirmation",
  "/contact",
  "/dashboard",
  "/forgot-password",
  "/home",
  "/login",
  "/logout",
  "/orders/:orderId/invoice-pdf",
  "/package/:id",
  "/product/:id",
  "/profile",
  "/reset-password",
  "/shop",
  "/shop/:category",
] as const;
export type Path = (typeof routePaths)[number];

// all params for any given path get defined here...
export type Params = {
  "/admin/orders/:orderId/manufacturer-xlsx": { orderId: string };
  "/orders/:orderId/invoice-pdf": { orderId: string };
  "/package/:id": { id: string };
  "/product/:id": { id: string };
  "/shop/:category": { category: string };
};

// Utility type to extract the leaf nodes of Params
type LeafNodes<T> = T[keyof T];

// Merge all leaf nodes into one big object type
type MergeLeafNodes<T> = UnionToIntersection<LeafNodes<T>>;

// Utility type to convert a union type to an intersection type
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Combined type of all the leaf nodes
export type AllParams = MergeLeafNodes<Params>;

export const { Link, NavLink } = components<Path, Params>();
export const { useNavigate, useParams } = hooks<Path, Params>();
export const { redirect, generatePath } = utils<Path, Params>();
